Vagrant.configure("2") do |config|
    #config.vm.box = "ubuntu/focal64"
    config.vm.box = "generic/ubuntu2004"
    #config.vm.provider "virtualbox" do |vb|
    #    vb.customize ["modifyvm", :id, "--memory", "4096"]
    #config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provision :shell, path: "mysql.sh"
    #config.vm.network :forwarded_port, guest: 3306, host: 3306
    #config.vm.network :forwarded_port, guest: 80, host: 80
    #config.vm.network "public_network"
end