Vagrant.configure("2") do |config|
  config.vm.define "api" do
    config.vm.provider "docker" do |d|
      d.image = "node"
    end
  end

  config.vm.define "db" do
    config.vm.provider "docker" do |d|
      d.image = "mongo"
    end
  end
end