#!/bin/bash

# Instalation with helm

helm repo add jenkinsci https://charts.jenkins.io
helm repo update

helm search repo jenkinsci

kubectl create namespace jenkins

wget -o jenkins-volume.yaml https://raw.githubusercontent.com/installing-jenkins-on-kubernetes/jenkins-volume
.yaml

kubectl apply -f jenkins-volume.yaml

https://raw.githubusercontent.com/installing-jenkins-on-kubernetes/jenkins-sa.yaml 

kubectl apply -f jenkins-sa.yaml 

wget https://raw.githubusercontent.com/jenkinsci/helm-charts/main/charts/jenkins/values.yaml

#reemplazar valores en values.yaml
#nodePort:32000
#storageClass: jenkins-pv

#serviceAccount:
#  create: false
# Service account name is autogenerated by default
#name: jenkins
#annotations: {}

chart=jenkinsci/jenkins
helm install jenkins -n jenkins -f jenkins-values.yaml $chart

jsonpath="{.data.jenkins-admin-password}"
secret=$(kubectl get secret -n jenkins jenkins -o jsonpath=$jsonpath)
echo $(echo $secret | base64 --decode)

RJSlwWvXlS4bWRP0GxYB3u

jsonpath="{.spec.ports[0].nodePort}"
NODE_PORT=$(kubectl get -n jenkins -o jsonpath=$jsonpath services jenkins)
jsonpath="{.items[0].status.addresses[0].address}"
NODE_IP=$(kubectl get nodes -n jenkins -o jsonpath=$jsonpath)
echo http://$NODE_IP:$NODE_PORT/login

http://192.168.65.4:/login